-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 22:44:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `academia` ;

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`ocupacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`ocupacion` ;

CREATE TABLE IF NOT EXISTS `academia`.`ocupacion` (
  `id_ocupacion` INT NOT NULL AUTO_INCREMENT,
  `ocupacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ocupacion`),
  UNIQUE INDEX `ocupacion_UNIQUE` (`ocupacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`usuario` ;

CREATE TABLE IF NOT EXISTS `academia`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ap_paterno` VARCHAR(45) NOT NULL,
  `ap_materno` VARCHAR(45) NULL,
  `email` VARCHAR(254) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `rol` ENUM('empleado', 'proveedor', 'admin') NOT NULL DEFAULT 'empleado',
  `autodescripcion` VARCHAR(200) NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `foto_perfil_url` VARCHAR(255) NULL,
  `id_ocupacion` INT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_ocupacion_idx` (`id_ocupacion` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_ocupacion`
    FOREIGN KEY (`id_ocupacion`)
    REFERENCES `academia`.`ocupacion` (`id_ocupacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`tipo_evento` ;

CREATE TABLE IF NOT EXISTS `academia`.`tipo_evento` (
  `id_tipo_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`recursos_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`recursos_evento` ;

CREATE TABLE IF NOT EXISTS `academia`.`recursos_evento` (
  `id_recursos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_recursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`evento` ;

CREATE TABLE IF NOT EXISTS `academia`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` TEXT(200) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  `grabacion_url` VARCHAR(255) NULL,
  `portada` VARCHAR(255) NOT NULL,
  `fecha_evento` DATETIME NULL,
  `id_tipo_evento` INT NOT NULL,
  `id_recursos` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_evento_tipo_evento1_idx` (`id_tipo_evento` ASC) VISIBLE,
  INDEX `fk_evento_recursos_evento1_idx` (`id_recursos` ASC) VISIBLE,
  CONSTRAINT `fk_evento_tipo_evento1`
    FOREIGN KEY (`id_tipo_evento`)
    REFERENCES `academia`.`tipo_evento` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_recursos_evento1`
    FOREIGN KEY (`id_recursos`)
    REFERENCES `academia`.`recursos_evento` (`id_recursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario_seguidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`usuario_seguidor` ;

CREATE TABLE IF NOT EXISTS `academia`.`usuario_seguidor` (
  `id_seguido` INT NOT NULL,
  `id_seguidor` INT NOT NULL,
  PRIMARY KEY (`id_seguido`, `id_seguidor`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`id_seguidor` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`id_seguido` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`id_seguido`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`id_seguidor`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`favorito` ;

CREATE TABLE IF NOT EXISTS `academia`.`favorito` (
  `id_usuario` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `fecha_favorito` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_evento`),
  INDEX `fk_usuario_has_evento_evento1_idx` (`id_evento` ASC) VISIBLE,
  INDEX `fk_usuario_has_evento_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_evento_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_evento_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `academia`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`evento_ponente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`evento_ponente` ;

CREATE TABLE IF NOT EXISTS `academia`.`evento_ponente` (
  `evento_id_evento` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`evento_id_evento`, `usuario_id_usuario`),
  INDEX `fk_evento_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_evento_has_usuario_evento1_idx` (`evento_id_evento` ASC) VISIBLE,
  CONSTRAINT `fk_evento_has_usuario_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `academia`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`etiqueta` ;

CREATE TABLE IF NOT EXISTS `academia`.`etiqueta` (
  `id_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre_etiqueta` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_etiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`evento_etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`evento_etiqueta` ;

CREATE TABLE IF NOT EXISTS `academia`.`evento_etiqueta` (
  `evento_id_evento` INT NOT NULL,
  `etiqueta_id_etiqueta` INT NOT NULL,
  PRIMARY KEY (`evento_id_evento`, `etiqueta_id_etiqueta`),
  INDEX `fk_evento_has_etiqueta_etiqueta1_idx` (`etiqueta_id_etiqueta` ASC) VISIBLE,
  INDEX `fk_evento_has_etiqueta_evento1_idx` (`evento_id_evento` ASC) VISIBLE,
  CONSTRAINT `fk_evento_has_etiqueta_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `academia`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_etiqueta_etiqueta1`
    FOREIGN KEY (`etiqueta_id_etiqueta`)
    REFERENCES `academia`.`etiqueta` (`id_etiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`comentario` ;

CREATE TABLE IF NOT EXISTS `academia`.`comentario` (
  `usuario_id_usuario` INT NOT NULL,
  `evento_id_evento` INT NOT NULL,
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT(100) NOT NULL,
  `calificacion` TINYINT(5) NULL,
  `fecha_comentario` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_usuario_has_evento_evento2_idx` (`evento_id_evento` ASC) VISIBLE,
  INDEX `fk_usuario_has_evento_usuario2_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_evento_usuario2`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_evento_evento2`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `academia`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`grupo` ;

CREATE TABLE IF NOT EXISTS `academia`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `academia`.`usuario_grupo` (
  `grupo_id_grupo` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`grupo_id_grupo`, `usuario_id_usuario`),
  INDEX `fk_grupo_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_grupo_has_usuario_grupo1_idx` (`grupo_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_has_usuario_grupo1`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `academia`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
